chore: limitting the gpu selection to one sku
Azure/karpenter pull request #77
Opened 2023-12-21 19:34 UTC by Bryce-Soghigian

Fixes # 

**Description**
When we use just the `n` series selector, we go through many instance types, we hit no quota for those gpu types a couple of times before successful provisioning for the "Standard_NC4as_T4_v3"  SKU. This just changes it to speed along this process. 
 
**How was this change tested?**
`/test`

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates
- [ ] Yes, issue opened: # 
- [x] No

**Release Note**

```release-note

```

2023-12-21 19:40 UTC, tallaxes reviewed
/test

2024-01-03 12:00 UTC, Bryce-Soghigian reviewed
/test

2024-01-04 18:39 UTC, Bryce-Soghigian reviewed
/test

2024-01-04 18:39 UTC, Bryce-Soghigian commented
going to run additional /test throughout the day to get some QOS on GPU

2024-01-04 19:44 UTC, Bryce-Soghigian reviewed
/test

2024-01-04 21:50 UTC, Bryce-Soghigian reviewed
/test

2024-01-04 22:22 UTC, Bryce-Soghigian reviewed
/test

2024-01-04 23:51 UTC, Bryce-Soghigian reviewed
/test

2024-01-05 01:59 UTC, Bryce-Soghigian reviewed
/test

2024-01-06 06:23 UTC, Bryce-Soghigian reviewed
/test

2024-01-10 22:47 UTC, charliedmcb requested changes
Assuming you've gotten a confirmed improved pass rate this is looking like a good change.

Please do update the PR description with a comment on the reasoning for the increased timeout as well, plus add links to the actual testing done, or at least more details of what you did as I believe it went beyond just one run of `/test`?

2024-01-10 22:47 UTC, charliedmcb commented on test/suites/gpu/suite_test.go
> +		// the Time.Minute 45 gives the test 3 tries to provision and bootstrap the node successfully
Add a TODO comment to try and improve this time requirement.

I don't have any problem with going up to 45 minutes if its improving the test pass rate for now, as I think that is more important currently. However, another side of QoS is complete runtime of the test, which is something we'll want to target to reduce as well

2024-01-13 08:29 UTC, closed without merging